#ifndef AIAPICONNECTENGINE_GLOBAL_H
#define AIAPICONNECTENGINE_GLOBAL_H
#pragma once

#include <QtCore/qglobal.h>

#if defined(AIAPICONNECTENGINE_LIBRARY)
#define AIAPICONNECTENGINE_EXPORT Q_DECL_EXPORT
#else
#define AIAPICONNECTENGINE_EXPORT Q_DECL_IMPORT
#endif

#endif // AIAPICONNECTENGINE_GLOBAL_H
