#ifndef TFILESCOPEPLUGIN_GLOBAL_H
#define TFILESCOPEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TFILESCOPEPLUGIN_LIBRARY)
#  define TFILESCOPEPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define TFILESCOPEPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // TFILESCOPEPLUGIN_GLOBAL_H
