#ifndef TANALTESTINGPLUGIN_GLOBAL_H
#define TANALTESTINGPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TANALTESTINGPLUGIN_LIBRARY)
#  define TANALTESTINGPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define TANALTESTINGPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // TANALTESTINGPLUGIN_GLOBAL_H
