#ifndef TDUMMYSCOPEPLUGIN_GLOBAL_H
#define TDUMMYSCOPEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TDUMMYSCOPEPLUGIN_LIBRARY)
#  define TDUMMYSCOPEPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define TDUMMYSCOPEPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // TDUMMYSCOPEPLUGIN_GLOBAL_H
